### ISSUE TITLE
Unexpected token ; when running from Command Line and from /examples/

### ISSUE THREAD

**Issue by AndrewCrider** [artpi/roam-research-private-api#10]
I attempted to run from both the command line for search and download.  Consistently getting the below error when using the CLI and running the example files. 

```
(base)  roam-research-private-api/examples % node download.js        
/usr/local/lib/node_modules/roam-research-private-api/RoamPrivateApi.js:13
	options;
	       ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/roam-research-private-api/examples/download.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Comment by dimfeld** [comment]
See https://github.com/artpi/roam-research-private-api/issues/9#issuecomment-780355740 for an explanation. I think newer versions of Node support this natively but I'm not sure which ones exactly.
