### ISSUE TITLE
Error when login in

### ISSUE THREAD

**Issue by pomdtr** [artpi/roam-research-private-api#2]
It looks like your script has an issue finding the correct input field in the login form.

```
/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: No node found for selector: input[name=email]
    at Object.exports.assert (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.type (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:306:21)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async RoamPrivateApi.logIn (/usr/local/lib/node_modules/roam-research-private-api/RoamPrivateApi.js:55:3)
    at async RoamPrivateApi.quickCapture (/usr/local/lib/node_modules/roam-research-private-api/RoamPrivateApi.js:87:3)
```

**Comment by artpi** [comment]
Are you using login / password combo or a google login?

**Comment by balOS** [comment]
unfortunately i now have google login (after initially signing up with login/pw) - any workarounds for that?

**Comment by artpi** [comment]
No, unfortunately not
