### ISSUE TITLE
TimeoutError: waiting for selector `.bp3-icon-more` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by bph** [artpi/roam-research-private-api#6]
In the same call as #5 an additional error showed: I have the feeling they are not connected, but could be wrong. .... 

- Node: version 14.15
- npm version 6.14.10 

TimeoutError: waiting for selector `.bp3-icon-more` failed: timeout 30000ms exceeded

(node:10362) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `.bp3-icon-more` failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    at Frame.waitForSelector (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/usr/local/lib/node_modules/roam-research-private-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    at RoamPrivateApi.logIn (/usr/local/lib/node_modules/roam-research-private-api/RoamPrivateApi.js:59:19)
    at async RoamPrivateApi.quickCapture (/usr/local/lib/node_modules/roam-research-private-api/RoamPrivateApi.js:87:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10362) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10362) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bph** [comment]
No sure if it's connected: I have a two word password, and after I added single quotes around the string, I could post the Quick Capture example to the website. And the #5 message was displayed three times.

**Comment by bph** [comment]
I close this for now. Happy Sunday! :-)
